### ISSUE TITLE
Setup development environment

### ISSUE THREAD

**Issue by GeetikaSi** [vathes/bl_pipeline_python_toArchive#13]
- [x] VPN setup prior to meeting
- [ ] Shan's workstation
    - [x] Access
    - [ ] Mount drives (archive and cup drives)
    - [ ] Clone repos
    - [x] Setup conda (conda activate error: get it working by Tuesday Nov 2)
 <img width="777" alt="Screen Shot 2021-10-28 at 2 35 23 PM" src="https://user-images.githubusercontent.com/58897783/139323560-9b4e92b7-271a-498b-9bbe-09d2fdf9823d.png">

- [x] Access datajoint00 and datajoint01 databases 
- [ ] Run the pipeline
- [ ] SQLWorkbench, get familiar with DJ cmd

**Comment by kabilar** [comment]
Hi @GeetikaSi, is this `Issue` complete?  Thank you.

**Comment by GeetikaSi** [comment]
Hi @kabilar , Yes, this is completed. Closing it now
